version: '3'
services:
  redis-cache:
    image: redis:7.0
  what-the-weather-node:
    image: 747901826397.dkr.ecr.eu-west-2.amazonaws.com/what-the-weather:latest
    ports:
      - 80:3000
    environment:
      - STAGE=prod
      - CACHE_USERNAME=default
      - CACHE_DATABASE_ADDRESS=redis-11223.c1.eu-west-1-3.ec2.cloud.redislabs.com
      - CACHE_DATABASE_PORT=11223
      - GEOLOCATION_BASEURL=http://api.ipstack.com
      - GEOLOCATION_BASEURL2=https://api.ipgeolocation.io/ipgeo
      - WEATHER_BASEURL=https://api.openweathermap.org/data/2.5/weather
      - CORS_ORIGIN=https://what-the-weather-1.herokuapp.com
